# README #

This repository provides programs that were used to generate figures in the article:
Alona Ben-Tal, Yunjiao Wang & Maria C.A. Leite. The logic behind neural control of breathing pattern. 
Scientific Reports (2019).  

The programs are provided with no gaurenty. They can be used and changed freely. 
We only ask that if you use our programs, you cite our work appropriatly. 

### How do I get set up? ###

* To generate Figures: 1C, 1D, 3 and 6, you need to have Matlab installed on your computer.
* To generate Figures: 4 and 5, you need Matlab, R, the package R.matlab and the package ggplot2.

R can be downloaded from https://cran.r-project.org .
Install R.Matlab by the command: install.packages('R.matlab') .
You also need the command: install.packages('ggplot2') .


To generate Fig. 3, use TrajectoryGenerator_3Nodes_plot.m .
To generate Fig.6, use TrajectoryGenerator_3Nodes_plot.m with the choice of parameters following the figure caption.
To generate Fig.4 and Fig.5,  check BoxPlotAll.html .

All remaining files are either functions called by the m-files mentioned above or .mat files that are generated 
by dataGenerator_for_BoxPlot.m, which is mentioned in BoxPlotAll.html. 


### Who do I talk to? ###

* Repo owner: Yunjiao Wang, e-mail: Yunjiao.Wang@tsu.edu
* Alona Ben-Tal, e-mail: a.ben-tal@massey.ac.nz